### PR TITLE
Allow deploying logrotate jobs using support meta

### PR DESCRIPTION
**Pull request by fpytloun**

### CODE REVIEW

**Comment by mnederlof** [comment]
@fpytloun, is there something going wrong with the tests here (pending for 5 days now i think ?)

**Comment by fpytloun** [comment]
Travis tests are fine, default is old obsolete infra that will be decomissioned soon.
BTW do you have some infra where we can test this change?

**Comment by mnederlof** [comment]
i can test it in our live environment if that is what you mean.

**Comment by fpytloun** [comment]
You will need to apply this patch + meta/logrotate.yml for horizon
And have pillar to enable logrotate:
```
logrotate:
  server:
    enabled: true
```
Then `salt-call state.sls logrotate` should generate horizon logrotate file.

I don't have env with horizon where I could test it right now but I think I can at least test this logrotate change during the day.

**Comment by mnederlof** [comment]
Tested it, needs one small change:

on line 9, change from
`{%- set _jobs = server.job %}`
to:
`{%- set _jobs = server.get('job', {}) %}`

It did not work, because i had no jobs configured yet.

Then it works like it is supposed to:
<pre>
node-12312-3:
  Name: logrotate - Function: pkg.installed - Result: Clean Started: - 12:28:21.448588 Duration: 455.243 ms
----------
          ID: logrotate_job_horizon
    Function: file.managed
        Name: /etc/logrotate.d/horizon
      Result: None
     Comment: The file /etc/logrotate.d/horizon is set to be changed
     Started: 12:28:21.905976
    Duration: 55.873 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -1,23 +1,16 @@
                  -/var/log/horizon/*.log {
                  -  compress
                  -  delaycompress
                  -  missingok
                  -  notifempty

                  -  # number of rotated files to keep
                  -  rotate 10
                  -
                  -  # do not rotate files unless both size and time conditions are met
                  -  daily
                  -  minsize 20M
                  -
                  -  # force rotate if filesize exceeded 100M
                  -  maxsize 500M
                  -
                  -  postrotate
                  -          if /etc/init.d/apache2 status > /dev/null ; then \
                  -              /etc/init.d/apache2 reload > /dev/null; \
                  -          fi;
                  -  endscript
                  +/var/log/horizon/*.log
                  +{
                  +    compress
                  +    delaycompress
                  +    missingok
                  +    notifempty
                  +    rotate 10
                  +    daily
                  +    minsize 20M
                  +    maxsize 500M
                  +    postrotate
                  +        if /etc/init.d/apache2 status > /dev/null; then /etc/init.d/apache2 reload > /dev/null; fi
                  +    endscript
                   }


Summary for node-12312-3
------------
Succeeded: 2 (unchanged=1, changed=1)
Failed:    0
------------
Total states run:     2
Total run time: 511.116 ms
</pre>

**Comment by fpytloun** [comment]
Awesome, thank you! :-)

**Review by epcim — APPROVED** [review]

**Pull request merged**
